version: "3.7"

services:
  review_api:
    container_name: "review_services_api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8091:8091"
    networks:
      - review_network
    env_file:
      - ./.env

  review_db:
    container_name: "review_services_db"
    platform: linux/x86_64
    image: mongo:4.4.6
    networks:
      - review_network
    restart: always
    ports:
      - "27016:27017"
    env_file:
      - ./.env

    volumes:
      - review_database:/data/db

networks:
  review_network:
volumes:
  review_database:
