version: "3.7"

services:
  api:
    container_name: "review_services_api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8091:8091"
    networks:
      - review_network
    env_file:
      - ./.env

  db:
    container_name: "review_services_db"
    platform: linux/x86_64
    # build:
    #   context: .
      # dockerfile: db.Dockerfile
    image: mongo:4.4.6
    networks:
      - review_network
    restart: always
    ports:
      # <Port exposed> : < Mongo Port running inside container>
      - "27016:27017"
    env_file:
      - ./.env

    volumes:
      - database:/data/db

networks:
  review_network:
volumes:
  database:
